COLUMNS:
  Identifiant de document: string
  Reference document: string
  1 Articles CGI: string
  2 Articles CGI: string
  3 Articles CGI: string
  4 Articles CGI: string
  5 Articles CGI: string
  No disposition: string
  Date mutation: date
  Nature mutation: string
  Valeur fonciere: float
  No voie: string
  B/T/Q: string
  Type de voie: string
  Code voie: string
  Voie: string
  Code postal: int
  Commune: string
  Code departement: string
  Code commune: string
  Prefixe de section: string
  Section: string
  No plan: string
  No Volume: string
  1er lot: string
  Surface Carrez du 1er lot: float
  2eme lot: string
  Surface Carrez du 2eme lot: float
  3eme lot: string
  Surface Carrez du 3eme lot: float
  4eme lot: string
  Surface Carrez du 4eme lot: float
  5eme lot: string
  Surface Carrez du 5eme lot: float
  Nombre de lots: int
  Code type local: string
  Type local: string
  Identifiant local: string
  Surface reelle bati: float
  Nombre pieces principales: int
  Nature culture: string
  Nature culture speciale: string
  Surface terrain: float


TARGET_COLUMN:
  name: Valeur fonciere
